### ISSUE TITLE
Migrate from NativeScript 5 to 6 

### ISSUE THREAD

**Issue by AnnBenavides** [ConnectyCube/connectycube-nativescript-samples#2]
Hello, i wanted to play with this source code, but the system make me migrate it to the newest version of NS and that brings a lot of errors and problems, strating with the webpack file, do you already migrate this source code?

**Comment by DaveLomber** [comment]
Hi @AnnBenavides 

we have not migrated it yet to the newest ver

what version are you trying to run ?

**Comment by DaveLomber** [comment]
Nevermind, I see it's 5 to 6 ;-D

**Comment by AnnBenavides** [comment]
Hello @DaveLomber 
are you planning to do it soon? Because i want to use connectycube in my grade project at uni, and i don't have much time :(

**Comment by DaveLomber** [comment]
@AnnBenavides the code sample is migrated to NS 6 

If there are any issues - lease raise a ticket 

thank you
